# Generated by Django 5.2.8 on 2025-11-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_site', '0004_produto_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
