# Generated by Django 5.2.8 on 2025-11-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_site', '0006_alter_produto_preco_caracteristica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_vendedor',
            field=models.BooleanField(default=False),
        ),
    ]
