# Generated by Django 5.2.8 on 2025-11-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_site', '0007_usuario_is_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
