# Generated by Django 5.2.7 on 2025-11-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_site', '0009_favorito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
